[build-system]
requires = [
    # Essentials
    "setuptools >= 42",

    # Plugins
    #"setuptools_scm[toml] >= 7.0.4",
    "setuptools_scm[toml] == 7.0.5.dev3+g3234d72",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "demo/_scm_version.py"
